# Lidr processing of point cloud - DTM Generation and Heigth above ground calculation

library(lidR)
library(sp)
library(terra)
library(lubridate)
library(RColorBrewer)
library(ggplot2)
library(MASS)
library(splines)
library(rgeos)
library(tidyverse)
library(viridis)
library(gridExtra)
library(DescTools)
library(sf)
library(exactextractr)
library(writexl) 
library (raster)
library(dplyr)
library(remotes)
library(cowplot)
library(reshape2)
library(readxl)
library(tictoc)
library(gstat)

# load in sample area
#P1_clip <- vect("E:/Glenn/Reproducibility/Plot/P1.shp")

P1_sf <- read_sf(dsn = "E:/Glenn/Reproducibility/Plot", layer = "P1")
P45_sf <- read_sf(dsn = "E:/Glenn/Reproducibility/Plot", layer = "P45")


#Read P1 and P45 las files from survey 1 
#
#S1_P1_las = readLAS( "E:/Glenn/Reproducibility/Processed/LAS/Plots/S1_P1.las")
S1_P45_las = readLAS("E:/Glenn/Reproducibility/Processed/LAS/Plots/S1_P45a.laz")
S1_P45_las_w = readLAS("E:/Glenn/Reproducibility/Processed/LAS/Plots/S1_P45_w.laz")

#Read in all plot DTMs generated by TIN in previous script
All_DTM = rast("E:/Glenn/Reproducibility/Plot/All_dtm_1cm.tif" )

# Height calc

nlas <- S1_P45_las  - All_DTM
plot(nlas, size = 1, bg = "grey")

#CHM raster - point to raster

chm <- rasterize_canopy(nlas, res = .01, algorithm = p2r())
col <- height.colors(25)
plot(chm, col = col)

chm <- rasterize_canopy(nlas, res = .01, algorithm = p2r())
col <- height.colors(25)
plot(chm, col = col)

#writeRaster(chm,"E:/Glenn/Reproducibility/Plot/P45a_chm.tif" , overwrite = TRUE)

#terra method of hole filling
fill.na <- function(x, i=5) { if (is.na(x)[i]) { return(mean(x, na.rm = TRUE)) } else { return(x[i]) }}
w <- matrix(1, 7, 7)
filled <- terra::focal(chm, w, fun = fill.na)
plot(filled, col = col)



#difference between filled and raw data
diff1 <- filled -chm
plot(diff1, col = col)

#Lidr TIN version of hole filling during ratserisation
chmtin <- rasterize_canopy(nlas, res = 0.01, algorithm = dsmtin())
plot(chmtin, col = col)

#difference
diff2 <- chmtin -chm
plot(diff2, col = col)

nlas_w <- S1_P45_las_w  - All_DTM
#plot(nlas_w, size = 1, bg = "grey")


#wider plot size TIN
chmtin_w <- rasterize_canopy(nlas_w, res = 0.01, algorithm = dsmtin())
plot(chmtin_w, col = col)

#writeRaster(chmtin_w,"E:/Glenn/Reproducibility/Plot/P45_chmtin_w.tif", overwrite = TRUE )


aoi_terra <- vect(P45_sf)
aoi_terra


ras_crop <- crop(chmtin_w, aoi_terra)
plot (ras_crop)
ras_mask <- mask(ras_crop, aoi_terra)
plot(ras_mask)
# ras_mask
# chmtin_w
# chmtin
# 
# diff3 <- ras_mask -chm
# plot(diff3, col = col)
# 
# diff4 <- ras_mask -chmtin
# plot(diff4, col = col)

writeRaster(ras_mask,"E:/Glenn/Reproducibility/Plot/P45a_chmtin_w.tif", overwrite = TRUE )

# Pit free method

chmpf <- rasterize_canopy(nlas, res = 0.01, pitfree(max_edge = c(0, 0.1)))
plot(chmpf, col = col)

chmpf_w <- rasterize_canopy(nlas_w, res = 0.01, pitfree(max_edge = c(0, 0.5)))
plot(chmpf_w, col = col)

ras_crop <- crop(chmpf_w, aoi_terra)
plot (ras_crop)
ras_mask_w <- mask(ras_crop, aoi_terra)
plot(ras_mask_w)


chmpf_w <- rasterize_canopy(nlas_w, res = 0.02, pitfree(max_edge = c(0, 0.5)))
plot(chmpf_w, col = col)

ras_crop <- crop(chmpf_w, aoi_terra)
plot (ras_crop)
ras_mask_w <- mask(ras_crop, aoi_terra)
plot(ras_mask_w)

# Uisng ratserize terrain

idw_dtm <- rast( "E:/Glenn/Reproducibility/Plot/P45_IDW3.tif" )

nlas_idw <- S1_P45_las  - idw_dtm

chm_idw <- rasterize_canopy(nlas_idw,res = 0.01, pitfree(max_edge = c(0, 0.5)))
plot(chm_idw, bg = "black") 

#difference
diff2 <- chm_idw -chm
plot(diff2, col = col)




#Terra hole filling 

x <- rast("E:/Glenn/Reproducibility/Plot/P45a_chm.tif")
# x[x==0] <- NA
plot(x)
x
hist(x)

idw <- terra::interpIDW(x, as.points(x), field="Z", radius=0.1, power=1, smooth=0, maxPoints=5) 

plot(x)
plot(idw)

xfill <- x

xfill[is.na(x)] <- idw

plot(xfill)

#gstat vesion

library(terra)
library(gstat)

pfunc <- function(.x, .idw) {
  par(mfrow = c(1, 2))
  plot(.x)
  plot(.idw)
  par(mfrow = c(1, 1))
}

#x <- rast("P45a_chm.tif")

gs <- gstat(formula=Z~1, locations=~x+y, data=as.data.frame(x, xy=TRUE))
idw <- interpolate(x, gs, debug.level=0)[[1]]

diff <- x-idw

plot(diff)

plot(idw)
pfunc(x, idw)

writeRaster(idw,"E:/Glenn/Reproducibility/Plot/P45_gstat_idw.tif", overwrite = TRUE )

