# Lidr processing of point cloud - DTM Generation and Heigth above ground calculation

library(lidR)
library(sp)
library(terra)
library(lubridate)
library(RColorBrewer)
library(ggplot2)
library(MASS)
library(splines)
library(rgeos)
library(tidyverse)
library(viridis)
library(gridExtra)
library(DescTools)
library(sf)
library(exactextractr)
library(writexl) 
library (raster)
library(dplyr)
library(remotes)
library(cowplot)
library(reshape2)
library(readxl)
library(tictoc)
library(gstat)

# load in sample area
#P1_clip <- vect("E:/Glenn/Reproducibility/Plot/P1.shp")

P1_sf <- read_sf(dsn = "E:/Glenn/Reproducibility/Plot", layer = "P1")
P45_sf <- read_sf(dsn = "E:/Glenn/Reproducibility/Plot", layer = "P45")


#Read P1 and P45 las files from survey 1 
#
S1_P1_las = readLAS( "E:/Glenn/Reproducibility/Processed/LAS/Plots/S1_P1.las")
S1_P45_las = readLAS("E:/Glenn/Reproducibility/Processed/LAS/Plots/S1_P45.las")

#Read in all plot DTMs generated by TIN
All_DTM = rast("E:/Glenn/Reproducibility/Plot/All_dtm_1cm.tif" )


#Calculate HAG - Normalised height las

nlas <- S1_P45_las  - All_DTM
plot(nlas, size = 1, bg = "grey")

# use point to raster to get CHM 

chm <- rasterize_canopy(nlas, res = .01, algorithm = p2r())
col <- height.colors(25)
plot(chm, col = col)

# use TIN to raster to get CHM 

chmtin <- rasterize_canopy(nlas, res = 0.01, algorithm = dsmtin())
plot(chmtin, col = col)

#or process as raster

fill.na <- function(x, i=5) { if (is.na(x)[i]) { return(mean(x, na.rm = TRUE)) } else { return(x[i]) }}
w <- matrix(1, 7, 7)
filled <- terra::focal(chm, w, fun = fill.na)
smoothed <- terra::focal(chm, w, fun = mean, na.rm = TRUE)

chms <- c(chm, filled, smoothed)
names(chms) <- c("Base", "Filled", "Smoothed")
plot(chms, col = col)

writeRaster(filled, "E:/Glenn/Reproducibility/Plot/filled.tif" )

r <- rast(ncol=100, nrow=100, crs="local", xmin=0, xmax=50, ymin=0, ymax=50)
set.seed(100)
x <- runif(25, 5, 45)
y <- runif(25, 5, 45)
z <- sample(25)
xyz <- cbind(x,y,z)

x <- interpIDW(r, xyz, radius=5, power=1, smooth=1, maxPoints=5)

plot(x)

r <- rast(ncol=100, nrow=100, crs="local", xmin=0, xmax=50, ymin=0, ymax=50)
set.seed(100)
x <- runif(25, 5, 45)
y <- runif(25, 5, 45)
z <- sample(25)
xyz <- cbind(x,y,z)

x <- interpIDW(r, xyz, radius=5, power=1, smooth=1, maxPoints=5)

plot(x)

